# Generated by Django 3.2.24 on 2024-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'public',
                'managed': False,
            },
        ),
    ]
